name: CI
on:
  push:
    branches:
      - translation-ja
    paths:
      - ".github/actions/workflows/main.yml"
      - "src/**"
      - "listings/**"
      - "redirects/**"
      - "theme/**"
      - "book.toml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: 'latest'

      - run: mdbook build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          external_repository: misogohan/book
          publish_branch: gh-pages-ja
          publiah_dir: ./book
